### ISSUE TITLE
OutOfMemory

### ISSUE THREAD

**Issue by GFOXSH** [Fuzion24/AndroidZipArbitrage#10]
Hello! Please, tell me how to fix following error:
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at java.lang.reflect.AccessibleObject.invokeV(AccessibleObject.java:364)
    at java.lang.reflect.Method.invokeNative(Method.java:682)
    at java.lang.reflect.ReflectAccess.invokeNavtive(ReflectAccess.java:106)
    at sun.reflect.ReflectionFactory.invokeNavtive(ReflectionFactory.java:335)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:636)
    at com.ibm.oti.vm.JarRunner.main(JarRunner.java:48)
Caused by: java.lang.OutOfMemoryError
    at java.util.Arrays.copyOf(Arrays.java:2271)
    at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:178)
    at utils.ZipFile.getZipFileBytes(ZipFile.scala:177)
    at android.zip.arbitrage.Main$$anonfun$7$$anonfun$apply$1$$anonfun$apply$2.apply(Main.scala:45)
    at android.zip.arbitrage.Main$$anonfun$7$$anonfun$apply$1$$anonfun$apply$2.apply(Main.scala:35)
    at scala.util.Success.foreach(Try.scala:205)
    at android.zip.arbitrage.Main$$anonfun$7$$anonfun$apply$1.apply(Main.scala:35)
    at android.zip.arbitrage.Main$$anonfun$7$$anonfun$apply$1.apply(Main.scala:34)
    at scala.util.Success.foreach(Try.scala:205)
    at android.zip.arbitrage.Main$$anonfun$7.apply(Main.scala:34)
    at android.zip.arbitrage.Main$$anonfun$7.apply(Main.scala:30)
    at scala.Option.map(Option.scala:145)
    at android.zip.arbitrage.Main$delayedInit$body.apply(Main.scala:30)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at android.zip.arbitrage.Main$.main(Main.scala:15)
    at android.zip.arbitrage.Main.main(Main.scala)
    at java.lang.reflect.AccessibleObject.invokeV(AccessibleObject.java:362)
    ... 7 more
Thank you in advace!

**Comment by GFOXSH** [comment]
OK, I fix it - APKs is too large.

**Comment by GFOXSH** [comment]
I delete all non-modifed files from APK, patch it and copy files back.
