### ISSUE TITLE
9695860 not compatible with OSX Java?

### ISSUE THREAD

**Issue by hubert3** [Fuzion24/AndroidZipArbitrage#8]
$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)

$ java -jar bin/AndroidZipArbitrage.jar --9695860 orig.apk patched.apk
Using Bug 9695860 to circumvent Android signatures
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/commons/compress/archivers/zip/ModdedZipArchiveOutputStream : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)

**Comment by hubert3** [comment]
Turns out you need Java 7 to run the jar. No errors with the following JRE on Linux:

$ java -version
java version "1.7.0_25"
OpenJDK Runtime Environment (IcedTea 2.3.10) (7u25-2.3.10-1ubuntu0.12.04.2)
OpenJDK Server VM (build 23.7-b01, mixed mode)

I would suggest putting a note in the README with compatible JREs.
